global:
 scrape_interval: 20s
 evaluation_interval: 20s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - kafka1:8080
      - kafka2:8080
      - kafka3:8080
 - job_name: 'zookeeper'
   static_configs:
    - targets:
      - zookeeper1:8080
      - zookeeper2:8080
      - zookeeper3:8080            